# 데이터 인코딩

# Mapping

In [1]:
pwd

'c:\\Users\\Jay\\Desktop\\python_ML\\perfect_guide'

In [43]:
import pandas as pd

df = pd.read_csv('C:/Users/Jay/Desktop/dacon/housing/train.csv')
df.head(10)

id  Overall Qual  Gr Liv Area Exter Qual  Garage Cars  Garage Area  \
0   1            10         2392         Ex            3          968   
1   2             7         1352         Gd            2          466   
2   3             5          900         TA            1          288   
3   4             5         1174         TA            2          576   
4   5             7         1958         Gd            3          936   
5   6             8         1968         Gd            3          680   
6   7             6         1478         TA            2          442   
7   8             8         2524         Gd            2          542   
8   9             8         2649         Gd            3          746   
9  10             8         1440         Gd            2          467   

  Kitchen Qual  Total Bsmt SF  1st Flr SF Bsmt Qual  Full Bath  Year Built  \
0           Ex           2392        2392        Ex          2        2003   
1           Gd           1352        1352        Ex          2        2006   
2           TA            864         900        TA          1        1967   
3           Gd            680         680        TA          1        1900   
4           Gd           1026        1026        Gd          2        2005   
5           Ex            774         774        Ex          2        2009   
6           TA           1478        1478        TA          1        1957   
7           Gd           2524        2524        Gd          2        1981   
8           Gd           1479        1515        Ex          2        2001   
9           Gd           1432        1440        Ex          2        2003   

   Year Remod/Add  Garage Yr Blt  target  
0            2003           2003  386250  
1            2007           2006  194000  
2            1967           1967  123000  
3            2006           2000  135000  
4            2005           2005  250000  
5            2010           2009  269500  
6            1957           1957  156500  
7            1981           1981  278000  
8            2002           2001  421250  
9            2003           2003  232500

In [44]:
df['Kitchen Qual'].value_counts()

TA    660
Gd    560
Ex    107
Fa     23
Name: Kitchen Qual, dtype: int64

In [45]:
kitchen_qual_map = {
    'Fa': 0,
    'TA': 1,
    'Gd': 2,
    'Ex': 3
}

df['Kitchen Qual'] = df['Kitchen Qual'].map(kitchen_qual_map)
df['Kitchen Qual'].head(10)

0    3
1    2
2    1
3    2
4    2
5    3
6    1
7    2
8    2
9    2
Name: Kitchen Qual, dtype: int64

In [46]:
df.head(10)

id  Overall Qual  Gr Liv Area Exter Qual  Garage Cars  Garage Area  \
0   1            10         2392         Ex            3          968   
1   2             7         1352         Gd            2          466   
2   3             5          900         TA            1          288   
3   4             5         1174         TA            2          576   
4   5             7         1958         Gd            3          936   
5   6             8         1968         Gd            3          680   
6   7             6         1478         TA            2          442   
7   8             8         2524         Gd            2          542   
8   9             8         2649         Gd            3          746   
9  10             8         1440         Gd            2          467   

   Kitchen Qual  Total Bsmt SF  1st Flr SF Bsmt Qual  Full Bath  Year Built  \
0             3           2392        2392        Ex          2        2003   
1             2           1352        1352        Ex          2        2006   
2             1            864         900        TA          1        1967   
3             2            680         680        TA          1        1900   
4             2           1026        1026        Gd          2        2005   
5             3            774         774        Ex          2        2009   
6             1           1478        1478        TA          1        1957   
7             2           2524        2524        Gd          2        1981   
8             2           1479        1515        Ex          2        2001   
9             2           1432        1440        Ex          2        2003   

   Year Remod/Add  Garage Yr Blt  target  
0            2003           2003  386250  
1            2007           2006  194000  
2            1967           1967  123000  
3            2006           2000  135000  
4            2005           2005  250000  
5            2010           2009  269500  
6            1957           1957  156500  
7            1981           1981  278000  
8            2002           2001  421250  
9            2003           2003  232500

# 레이블 인코딩(Label encoding)

In [3]:
from sklearn.preprocessing import LabelEncoder

items = ['TV','냉장고','전자렌지','컴퓨터','선풍기','선풍기','믹서','믹서']

# LabelEncoder 클래스를 encoder 객체로 생성한 후
encoder = LabelEncoder()

# fit은 transform 수행 전 틀을 맞춰주는 역할
encoder.fit(items)

# encoder.transform( ) 으로 label 인코딩 수행. 
labels = encoder.transform(items)
print('인코딩 변환값:', labels)

인코딩 변환값: [0 1 4 5 3 3 2 2]


In [4]:
print('인코딩 클래스:', encoder.classes_)

인코딩 클래스: ['TV' '냉장고' '믹서' '선풍기' '전자렌지' '컴퓨터']


In [5]:
print('디코딩 원본 값:', encoder.inverse_transform([0, 1, 4, 5, 3, 3, 2, 2]))

디코딩 원본 값: ['TV' '냉장고' '전자렌지' '컴퓨터' '선풍기' '선풍기' '믹서' '믹서']


# 원-핫 인코딩(One-Hot encoding)

## (1) sklearn에서의 원핫 인코딩

<sklearn에서의 원핫 인코딩은 좀 복잡하다>
1. 먼저 숫자값으로 변환을 위해 LabelEncoder로 변환합니다. 
2. 2차원 데이터로 변환합니다. (reshape 활용)
3. 원-핫 인코딩을 적용합니다. 

In [8]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

items=['TV','냉장고','전자렌지','컴퓨터','선풍기','선풍기','믹서','믹서']

# 첫번째, 먼저 숫자값으로 변환을 위해 LabelEncoder로 변환합니다. 
encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)
labels

array([0, 1, 4, 5, 3, 3, 2, 2])

In [13]:
# 두번째, 2차원 데이터로 변환합니다. 
labels = labels.reshape(-1, 1)
labels

array([[0],
       [1],
       [4],
       [5],
       [3],
       [3],
       [2],
       [2]])

In [14]:
# 마지막으로 원-핫 인코딩을 적용합니다.
oh_encoder = OneHotEncoder()
oh_encoder.fit(labels)
oh_labels = oh_encoder.transform(labels)

print('원-핫 인코딩 데이터')
print(oh_labels.shape)
oh_labels.toarray()

원-핫 인코딩 데이터
(8, 6)


array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.]])

## (2) 판다스의 원핫 인코딩

In [6]:
import pandas as pd

df = pd.DataFrame({'item':['TV','냉장고','전자렌지','컴퓨터','선풍기','선풍기','믹서','믹서'] })
df

item
0    TV
1   냉장고
2  전자렌지
3   컴퓨터
4   선풍기
5   선풍기
6    믹서
7    믹서

In [7]:
pd.get_dummies(df)

item_TV  item_냉장고  item_믹서  item_선풍기  item_전자렌지  item_컴퓨터
0        1         0        0         0          0         0
1        0         1        0         0          0         0
2        0         0        0         0          1         0
3        0         0        0         0          0         1
4        0         0        0         1          0         0
5        0         0        0         1          0         0
6        0         0        1         0          0         0
7        0         0        1         0          0         0

# 피처 스케일링과 정규화

## (1) StandardScaler

In [ ]:
from sklearn.datasets import load_iris
import pandas as pd

In [39]:
# 붓꽃 데이터 셋을 로딩하고 DataFrame으로 변환합니다. 
iris = load_iris()
iris_data = iris.data

In [40]:
iris_data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [41]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [42]:
iris_df = pd.DataFrame(data=iris_data, columns=iris.feature_names)

print('feature 들의 평균 값')
print(iris_df.mean(), '\n')

print('feature 들의 분산 값')
print(iris_df.var())

feature 들의 평균 값
sepal length (cm)    5.843333
sepal width (cm)     3.057333
petal length (cm)    3.758000
petal width (cm)     1.199333
dtype: float64 

feature 들의 분산 값
sepal length (cm)    0.685694
sepal width (cm)     0.189979
petal length (cm)    3.116278
petal width (cm)     0.581006
dtype: float64


In [43]:
from sklearn.preprocessing import StandardScaler

# StandardScaler객체 생성
scaler = StandardScaler()

# StandardScaler 로 데이터 셋 변환. fit( ) 과 transform( ) 호출.  
scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df)
iris_scaled

array([[-9.00681170e-01,  1.01900435e+00, -1.34022653e+00,
        -1.31544430e+00],
       [-1.14301691e+00, -1.31979479e-01, -1.34022653e+00,
        -1.31544430e+00],
       [-1.38535265e+00,  3.28414053e-01, -1.39706395e+00,
        -1.31544430e+00],
       [-1.50652052e+00,  9.82172869e-02, -1.28338910e+00,
        -1.31544430e+00],
       [-1.02184904e+00,  1.24920112e+00, -1.34022653e+00,
        -1.31544430e+00],
       [-5.37177559e-01,  1.93979142e+00, -1.16971425e+00,
        -1.05217993e+00],
       [-1.50652052e+00,  7.88807586e-01, -1.34022653e+00,
        -1.18381211e+00],
       [-1.02184904e+00,  7.88807586e-01, -1.28338910e+00,
        -1.31544430e+00],
       [-1.74885626e+00, -3.62176246e-01, -1.34022653e+00,
        -1.31544430e+00],
       [-1.14301691e+00,  9.82172869e-02, -1.28338910e+00,
        -1.44707648e+00],
       [-5.37177559e-01,  1.47939788e+00, -1.28338910e+00,
        -1.31544430e+00],
       [-1.26418478e+00,  7.88807586e-01, -1.22655167e+00,
      

In [46]:
# transform( )시 scale 변환된 데이터 셋이 numpy ndarry로 반환되어 이를 DataFrame으로 변환
iris_df_scaled = pd.DataFrame(data=iris_scaled, columns=iris.feature_names)

print('feature 들의 평균 값')
print(iris_df_scaled.mean(), '\n')

print('feature 들의 분산 값')
print(iris_df_scaled.var())

feature 들의 평균 값
sepal length (cm)   -1.690315e-15
sepal width (cm)    -1.842970e-15
petal length (cm)   -1.698641e-15
petal width (cm)    -1.409243e-15
dtype: float64 

feature 들의 분산 값
sepal length (cm)    1.006711
sepal width (cm)     1.006711
petal length (cm)    1.006711
petal width (cm)     1.006711
dtype: float64


## (2) MinMaxScaler

In [47]:
from sklearn.preprocessing import MinMaxScaler

# MinMaxScaler객체 생성
scaler = MinMaxScaler()

# MinMaxScaler 로 데이터 셋 변환. fit() 과 transform() 호출.  
scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df)

In [48]:
# transform()시 scale 변환된 데이터 셋이 numpy ndarry로 반환되어 이를 DataFrame으로 변환
iris_df_scaled = pd.DataFrame(data=iris_scaled, columns=iris.feature_names)

print('feature들의 최소 값')
print(iris_df_scaled.min(), '\n')

print('feature들의 최대 값')
print(iris_df_scaled.max())

feature들의 최소 값
sepal length (cm)    0.0
sepal width (cm)     0.0
petal length (cm)    0.0
petal width (cm)     0.0
dtype: float64 

feature들의 최대 값
sepal length (cm)    1.0
sepal width (cm)     1.0
petal length (cm)    1.0
petal width (cm)     1.0
dtype: float64
